/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


typedef int64_t Timestamp;

@interface IrisException_t : NSException <NSCoding> {
  int32_t __errorCode;
  NSString * __errorDesc;

  BOOL __errorCode_isset;
  BOOL __errorDesc_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=errorDesc, setter=setErrorDesc:) NSString * errorDesc;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode errorDesc: (NSString *) errorDesc;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) errorDesc;
- (void) setErrorDesc: (NSString *) errorDesc;
#endif
- (BOOL) errorDescIsSet;

@end

@interface Location_t : NSObject <NSCoding> {
  double __longitude;
  double __latitude;

  BOOL __longitude_isset;
  BOOL __latitude_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=longitude, setter=setLongitude:) double longitude;
@property (nonatomic, getter=latitude, setter=setLatitude:) double latitude;
#endif

- (id) init;
- (id) initWithLongitude: (double) longitude latitude: (double) latitude;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (double) longitude;
- (void) setLongitude: (double) longitude;
#endif
- (BOOL) longitudeIsSet;

#if !__has_feature(objc_arc)
- (double) latitude;
- (void) setLatitude: (double) latitude;
#endif
- (BOOL) latitudeIsSet;

@end

@interface CustomerMetadata_t : NSObject <NSCoding> {
  NSString * __customerId;
  NSString * __deviceId;
  NSString * __email;
  NSString * __ipAddress;
  Location_t * __location;

  BOOL __customerId_isset;
  BOOL __deviceId_isset;
  BOOL __email_isset;
  BOOL __ipAddress_isset;
  BOOL __location_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=customerId, setter=setCustomerId:) NSString * customerId;
@property (nonatomic, retain, getter=deviceId, setter=setDeviceId:) NSString * deviceId;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=ipAddress, setter=setIpAddress:) NSString * ipAddress;
@property (nonatomic, retain, getter=location, setter=setLocation:) Location_t * location;
#endif

- (id) init;
- (id) initWithCustomerId: (NSString *) customerId deviceId: (NSString *) deviceId email: (NSString *) email ipAddress: (NSString *) ipAddress location: (Location_t *) location;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) customerId;
- (void) setCustomerId: (NSString *) customerId;
#endif
- (BOOL) customerIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) deviceId;
- (void) setDeviceId: (NSString *) deviceId;
#endif
- (BOOL) deviceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) ipAddress;
- (void) setIpAddress: (NSString *) ipAddress;
#endif
- (BOOL) ipAddressIsSet;

#if !__has_feature(objc_arc)
- (Location_t *) location;
- (void) setLocation: (Location_t *) location;
#endif
- (BOOL) locationIsSet;

@end

@protocol Iris_t <NSObject>
- (void) getNotificationMessages: (CustomerMetadata_t *) customerMetadata;  // throws IrisException_t *, TException
@end

@interface Iris_tClient : NSObject <Iris_t> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface Iris_tProcessor : NSObject <TProcessor> {
  id <Iris_t> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithIris_t: (id <Iris_t>) service;
- (id<Iris_t>) service;
@end

@interface irisConstants : NSObject {
}
@end
